const apple = 
   [
    {
      name: "iPhone 14 - 128GB",
      slug: "iphone-14",
      category: "Iphones",
      image: "../public/images/Iphone14.jpg",
      price: 1000,
      rating: 4.5,
      countInStock: 20,
      description:
        " iPhone 14 - 128GB - Colors Midnight, Purple, Starlight, Red, Blue",
    },
    {
      name: "iPhone 13 - 128GB",
      slug: "iphone-13",
      category: "Iphones",
      image: "../public/images/Iphone13.jpg",
      price: 800,
      rating: 4.3,
      countInStock: 20,
      description: " iPhone 13 - 128GB - Colors Starlight, Midnight, Blue",
    },
    {
      name: "iPad Pro 11 M1 Chip - 128 GB WiFi",
      slug: "ipad-pro",
      category: "Ipads",
      image: "../public/images/IpadPro.jpg",
      price: 950,
      rating: 4.5,
      countInStock: 20,
      description: " iPad Pro 11 M1 Chip - 128 GB WiFi",
    },
    {
      name: "iPhone SE (3rd Gen) - 64 GB",
      slug: "iphone-se3",
      category: "Iphones",
      image: "../public/images/IphoneSE.jpg",
      price: 600,
      rating: 4.7,
      countInStock: 20,
      description: " iPhone SE (3rd Gen) - 64 GB",
    },
    {
      name: "MacBook Air 13.6 M2 Chip 256 GB - Midnight",
      slug: "macbook-air",
      category: "Macbooks",
      image: "../public/images/MacbookAir.jpg",
      price: 1500,
      rating: 4.5,
      countInStock: 20,
      description: " MacBook Air 13.6 M2 Chip 256 GB - Midnight",
    },
    {
      name: "Macbook Pro 13 [MNEH3] M2 - 256 GB - Space Gray",
      slug: "macbook-pro",
      category: "Macbooks",
      image: "../public/images/MacbookPro.jpg",
      price: 1400,
      rating: 4.4,
      countInStock: 20,
      description: " Macbook Pro 13 [MNEH3] M2 - 256 GB - Space Gray",
    },
    {
      name: "AirPods (3rd Gen)",
      slug: "airpods-3",
      category: "Airpods",
      image: "../public/images/Airpods3rdgen.jpg",
      price: 200,
      rating: 4.7,
      countInStock: 20,
      description: " AirPods (3rd Gen)",
    },
    {
      name: "AirPods Pro",
      slug: "airpods-pro",
      category: "Airpods",
      image: "../public/images/AirpodsPro.jpg",
      price: 230,
      rating: 4.6,
      countInStock: 20,
      description:
        " Los AirPods Pro tienen tecnología de cancelación activa de ruido para sumergirte en lo que escuchas, un modo de sonido ambiente para oír lo que pasa a tu alrededor y ajuste a medida para llevarlos puestos todo el día como si nada. Se conectan al iPhone y al Apple Watch como por arte de magia, igual que los AirPods. Y están listos para usar en cuanto los sacas del estuche.",
    },
    {
      name: "Apple Watch 7 SE",
      slug: "applewatch-7se",
      category: "Watches",
      image: "../public/images/AppleWatchSe.jpg",
      price: 380,
      rating: 4.5,
      countInStock: 20,
      description:
        " Apple Watch 40mm [SE] Gold Aluminum Case with Pink Sand Sport Band",
    },
    {
      name: "Apple Watch Series 7",
      slug: "applewatch-7",
      category: "Watches",
      image: "../public/images/AppleWatch7.jpg",
      price: 380,
      rating: 4.5,
      countInStock: 20,
      description:
        " Apple Watch 41mm [SERIES 7] Midnight Aluminum Case with Midnight Sport Band",
    },
  ]

export default apple;
